from procesadorXLS import procesarXLS
from procesadorDOC import procesarDOC
from procesadorPDF import procesarPDF
from procesadorDACE import procesarDACE
from funcionesAuxiliares import cargarMaterias, cargarOfertasCSV
